"""Initial migration

Revision ID: 34e433a0f27f
Revises: 
Create Date: 2026-02-21 04:24:04.753952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34e433a0f27f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('backtest_id', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('single_date', sa.Date(), nullable=True),
    sa.Column('target_delta', sa.Float(), nullable=False),
    sa.Column('put_distance', sa.Integer(), nullable=False),
    sa.Column('call_distance', sa.Integer(), nullable=False),
    sa.Column('spread_width', sa.Integer(), nullable=False),
    sa.Column('decay_threshold', sa.Float(), nullable=False),
    sa.Column('profit_target', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('entry_time', sa.String(length=8), nullable=False),
    sa.Column('monitor_interval', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('successful_trades', sa.Integer(), nullable=True),
    sa.Column('total_pnl', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('win_rate', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_backtest_id'), 'backtest_runs', ['backtest_id'], unique=True)
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('option_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('bid', sa.Float(), nullable=True),
    sa.Column('ask', sa.Float(), nullable=True),
    sa.Column('mid_price', sa.Float(), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('open_interest', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('gamma', sa.Float(), nullable=True),
    sa.Column('theta', sa.Float(), nullable=True),
    sa.Column('vega', sa.Float(), nullable=True),
    sa.Column('rho', sa.Float(), nullable=True),
    sa.Column('implied_volatility', sa.Float(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('data_source', sa.String(length=20), nullable=False),
    sa.Column('extra_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_data_date'), 'option_data', ['date'], unique=False)
    op.create_index(op.f('ix_option_data_expiration_date'), 'option_data', ['expiration_date'], unique=False)
    op.create_index(op.f('ix_option_data_strike'), 'option_data', ['strike'], unique=False)
    op.create_index(op.f('ix_option_data_symbol'), 'option_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_option_data_timestamp'), 'option_data', ['timestamp'], unique=False)
    op.create_index(op.f('ix_option_data_underlying_symbol'), 'option_data', ['underlying_symbol'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False),
    sa.Column('logger', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('function', sa.String(length=50), nullable=True),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('backtest_run_id', sa.UUID(), nullable=True),
    sa.Column('trade_id', sa.String(length=50), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_backtest_run_id'), 'system_logs', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_logs_trade_id'), 'system_logs', ['trade_id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trade_id', sa.String(length=50), nullable=False),
    sa.Column('backtest_run_id', sa.UUID(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('entry_time', sa.String(length=8), nullable=False),
    sa.Column('exit_time', sa.String(length=8), nullable=True),
    sa.Column('entry_spx_price', sa.Float(), nullable=False),
    sa.Column('exit_spx_price', sa.Float(), nullable=True),
    sa.Column('strategy_type', sa.String(length=20), nullable=False),
    sa.Column('strikes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('entry_credit', sa.Float(), nullable=False),
    sa.Column('exit_cost', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pnl_percentage', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=50), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('max_profit', sa.Float(), nullable=True),
    sa.Column('max_loss', sa.Float(), nullable=True),
    sa.Column('strategy_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('monitoring_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_backtest_run_id'), 'trades', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_trades_trade_date'), 'trades', ['trade_date'], unique=False)
    op.create_index(op.f('ix_trades_trade_id'), 'trades', ['trade_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_trade_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_trade_date'), table_name='trades')
    op.drop_index(op.f('ix_trades_backtest_run_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_system_logs_trade_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_backtest_run_id'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_option_data_underlying_symbol'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_timestamp'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_symbol'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_strike'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_expiration_date'), table_name='option_data')
    op.drop_index(op.f('ix_option_data_date'), table_name='option_data')
    op.drop_table('option_data')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_backtest_runs_backtest_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
